version: '3'

services:
    nginx:
        container_name: container_nginx
        build:
            context: .
            dockerfile: Dockerfile-nginx
        volumes:
            - ./symfonytest/:/var/www/symfony/
        ports:
            - 8001:80
        networks:
            - symfonytest
    php:
        build:
            context: .
            dockerfile: Dockerfile-php
        environment:
            APP_ENV: dev
            DATABASE_URL: mysql://root:root@mysql:3306/symfony_test?serverVersion=5.7
        volumes:
            - ./symfonytest/:/var/www/symfony/
        networks:
            - symfonytest
        depends_on:
            - mysql
    mysql:
        container_name: container_mysql
        image: mysql
        cap_add:
          - SYS_NICE
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - symfonytest
networks:
    symfonytest:

